### ISSUE TITLE
Lint for redundant single arity ->> (thread-last macro)

### ISSUE THREAD

**Issue by zackteo** [clj-kondo/clj-kondo#1459] opened 2021-11-16 01:20 UTC
**Is your feature request related to a problem? Please describe.**
```clj
(->> [1 2 3 4 5])
```

**Describe the solution you'd like**
Was thinking if it might be worthwhile to add a lint on `->>` here as the macro is redundant

**Describe alternatives you've considered**
Perhaps this should be something people would just not do anyway

**Additional context**
Not sure if this might be a wanted lint, or if there is some strict mode in clj-kondo that already does this

[ Optional: if you are interested in doing a PR yourself, please leave a note. ]
If this might be a desirable feature and given that this should be quite a simple(?) PR, I would be interested in doing the PR myself

**Comment by borkdude** [comment] 2021-12-03 16:30
Duplicate of #1166

**Closed by borkdude** 2021-12-03 16:30 UTC
