### ISSUE TITLE
Add support for suppressing linter warnings in hooks

### ISSUE THREAD

**Issue by markbastian** [clj-kondo/clj-kondo#1980] opened 2023-02-01 23:24 UTC
See [this Slack thread](https://clojurians.slack.com/archives/CHY97NXE2/p1675289512599869) for context.

Fundamentally, if a ban happens via `:discouraged-vars` but a macro expansion that uses said vars occurs in an `:analyze-call` hook, the discouraged var will occur via expansion. A simple workaround is to just use a different symbol in the expansion, but it would be nice to be able to use the standard ignore hints (e.g. `#_{:clj-kondo/ignore [:discouraged-vars]}`) in the hook code.

Perhaps adding a metadata form of ignore wouldn't get lost (e.g. `^{:clj-kondo/ignore [:discouraged-vars]}`)?

**Comment by camsaul** [comment] 2023-02-02 00:47
The metadata version of `:clj-kondo/ignore` definitely already works for some linters -- we're using it for macros in Metabase here

https://github.com/metabase/metabase/blob/401edd07060a00f8962d81981bcb0aa12b628cd8/.clj-kondo/macros/common.clj#L4-L5 

https://github.com/metabase/metabase/blob/master/.clj-kondo/macros/401edd07060a00f8962d81981bcb0aa12b628cd8/api/collection_test.clj#L5

I've had some success making this work in hooks e.g.

https://github.com/camsaul/toucan2/blob/6e2eccf2d2af863ffc924c166c899e0f0f8391bc/resources/clj-kondo.exports/com.github.camsaul/toucan2/hooks/toucan2/tools/simple_out_transform.clj#L4-L5

I think the problem is that it only works it doesn't work consistently -- it seems to work find for `:unused-binding` but I've had trouble getting it to work for other linters, especially in hooks

**Comment by markbastian** [comment] 2023-02-02 14:56
I gave the [approach mentioned](https://github.com/camsaul/toucan2/blob/6e2eccf2d2af863ffc924c166c899e0f0f8391bc/resources/clj-kondo.exports/com.github.camsaul/toucan2/hooks/toucan2/tools/simple_out_transform.clj#L4-L5) a try and it didn't work for the `:discouraged-var` linter.

**Comment by borkdude** [comment] 2023-02-02 21:45
There aren't any tests or docs in clj-kondo suggesting that adding metadata with `:clj-kondo/ignore` to anything will ignore anything, so if that works, it's probably just co-incidental.

If you want to ignore unused bindings, I'd just generate bindings that start with an underscore, or use them explicitly, e.g. by producing a vector with those bindings in them.

The issue above should be fixed, but one approach to work around it, which I suggested on Slack, is this:

> One option is also to introduce a special print function in your code-base like: `metabase.utils/production-print` which uses `clojure.core/print` for production usage and you ignore it only there, and all other `clojure.core/print` usages are forbidden.

**Comment by borkdude** [comment] 2023-02-02 21:50
@markbastian I re-read your original post and it's different than how I understood it on slack. I thought what you meant on Slack was

```
#_:clj-kondo/ignore
(some-function-call-which-expands-using-a-hook)
```

vs what you probably mean above:

```
(defn my-hook [{:keys [node]}]
  (vary-meta node assoc :clj-kondo/ignore ...))
```

Those are two different things. 

Can you please fill out the issue template and give me a reproduction of this issue with example code that I can readily lint, preferably in a github repo?

**Comment by markbastian** [comment] 2023-02-08 20:06
I've put an example of this in [this branch](https://github.com/metabase/metabase/tree/kondo-hooks-1980-repro) of metabase. The change I added to reflect the warnings on expansion of hooks can be found [here](https://github.com/metabase/metabase/blob/kondo-hooks-1980-repro/.clj-kondo/hooks/metabase/test/data.clj#L72-L76). To see it in action, do the following:

- Install [pre-commit](https://pre-commit.com/) via `brew install pre-commit`
- Add a `.pre-commit-config.yaml` file to the project directory with the following contents:

```yaml
repos:
  -   repo: https://github.com/clj-kondo/clj-kondo
      rev: v2022.12.10
      hooks:
        - id: clj-kondo
```

- Add the hooks with `pre-commit install`
- Run `git ls-files -- 'test/*.clj*' | xargs pre-commit run --files` to run kondo on the test sources

Note that this is how I run kondo. It's probably easier to just run kondo on the `test` dir directly.

Expected: no print warnings
Actual: I get a large number of warnings like `test/metabase/query_processor_test/nested_field_test.clj:136:19: warning: Use clojure.tools.logging instead of clojure.core/print`

**Comment by borkdude** [comment] 2023-02-08 20:08
@markbastian Thanks!

**Comment by borkdude** [comment] 2023-02-10 20:20
@markbastian As @camsaul pointed out, you can suppress lint warnings by attaching metadata, like I showed here:

https://github.com/clj-kondo/clj-kondo/commit/5e1e07a5b437cda04317e4c1f42ccf9f38276b30

I didn't realize that this worked (and it's not documented anywhere) but I don't see why it shouldn't. So @camsaul: I'll write a test to capture this behavior and then I consider it supported :-)

**Closed** 2023-02-15 10:32 UTC
Labels: metabase
