### ISSUE TITLE
No `_` as last binding name

### ISSUE THREAD

**Issue by vemv** [clj-kondo/clj-kondo#1423] opened 2021-10-18 07:58 UTC
**Is your feature request related to a problem? Please describe.**

If the name of a last `let` binding is `_`, it can be moved to its body:

```diff
-(let [foo (bar)
-      _ (baz)]
+(let [foo (bar)]
+ (baz)
  (quux foo))
```

Doing so arguably decreases cognitive overhead.

**Describe the solution you'd like**

Lint against those redundant bindings (there can be N last redundant bindings in a given `let`).

Not sure of what to do with e.g. `_user`. Personally I'd also consider that a redundant binding despite the informative name.

(If you ask me, I prefer a comment to that binding name in this case if it's crucial to explain a return value).

Perhaps that nuance could be configurable.

Cheers - V

**Comment by borkdude** [comment] 2021-12-03 19:04
Duplicate of #904

**Closed by borkdude** 2021-12-03 19:04 UTC
