### ISSUE TITLE
Define third-party vars usage as deprecated (deprecated-var extension?)

### ISSUE THREAD

**Issue by Valdermeyder** [clj-kondo/clj-kondo#1207] opened 2021-03-09 15:19 UTC
**Is your feature request related to a problem? Please describe.**
The issue comes from [Slack conversation](https://clojurians.slack.com/archives/CHY97NXE2/p1615297899228100). Below is a short summary of it.

`clj-kondo` has a deprecated var linter: https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#deprecated-var
That could be useful, but it's done automatically if the var is marked deprecated in the third-party library already. But no way to add your own vars to that.
Similar stuff has been considered for `clojure.core/read-string` for example, but there are cases where you still might want to use that

**Describe the solution you'd like**
Extend `:deprecated-var` rule
`{:deprecated-var {foo.bar/baz foo.bar/quux}}` => "Var foo.bar/baz is deprecated. Use foo.bar/quux instead"

**Describe alternatives you've considered**
New rule
`{:new-rule-name {foo.bar/baz foo.bar/quux}}` => "Var foo.bar/baz is deprecated. Use foo.bar/quux instead"

**Comment by borkdude** [comment] 2021-12-03 16:38
I consider this a duplicate of #996

**Closed by borkdude** 2021-12-03 16:38 UTC
Labels: wontfix
