### ISSUE TITLE
Improve clj-kondo to detect type hints for method returns 

### ISSUE THREAD

**Issue by ieugen** [clj-kondo/clj-kondo#1572] opened 2022-02-08 13:32 UTC
To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

**Is your feature request related to a problem? Please describe.**

clj-kondo does not find the usage of ^List type hint:

```
clj-kondo --lint src/clj/user.clj 
src/clj/user.clj:2:34: warning: Unused import List
linting took 30ms, errors: 0, warnings: 1
```
The file is like this (extracted from from clj-commons/claypool/ ). 
```clojure

(ns user
  (:import [java.util Collection List]
           [java.util.concurrent
            ExecutorService
            TimeUnit]))

;; clj-kondo does not see the usage of ^List type hint in return type ?! 
(deftype PriorityThreadpool [pool, priority-fn]
  ExecutorService
  (^boolean awaitTermination [_, ^long timeout, ^TimeUnit unit]
    (.awaitTermination pool timeout unit))
  (^List invokeAll [_, ^Collection tasks]
    (.invokeAll pool (println tasks)))
  (^List invokeAll [_, ^Collection tasks, ^long _timeout, ^TimeUnit _unit]
    (.invokeAll pool (println tasks)))
  (^Object invokeAny [_, ^Collection tasks]
    (.invokeAny pool (println tasks)))
  (^Object invokeAny [_, ^Collection tasks, ^long _timeout, ^TimeUnit _unit]
    (.invokeAny pool (println tasks)))
  (^boolean isShutdown [_]
    (.isShutdown pool))
  (^boolean isTerminated [_]
    (.isTerminated pool))
  (shutdown [_]
    (.shutdown pool))
  (^List shutdownNow [_]
    (.shutdownNow pool))
  (^Future submit [_, ^Runnable task]
    (.submit pool ^Runnable (println task)))
  (^Future submit [_, ^Runnable task, ^Object result]
    (.submit pool ^Runnable (println task) result))
  (^Future submit [_ ^Callable task]
    (.submit pool ^Callable (println task))))

```

**Describe the solution you'd like**

clj-kondo should not report List as un-used. 

**Additional context**

The solution to this issue might be used also for https://github.com/clj-kondo/clj-kondo/issues/1544

**Comment by borkdude** [comment] 2022-02-09 19:28
This is a duplicate of #1540 and was already fixed on master.

**Closed by borkdude** 2022-02-09 19:28 UTC
