### ISSUE TITLE
report always truthy seqs in condition clauses

### ISSUE THREAD

**Issue by dpsutton** [clj-kondo/clj-kondo#1486] opened 2021-12-06 18:23 UTC
To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

**Is your feature request related to a problem? Please describe.**

I caught the following bug in a PR review. Empty seqs are truthy of course, so the `when` here will always be taken. We, as readers, know this code really means when strings (are found). It would be nice if clj-kondo could report this as an error, also possibly suggesting to use `seq`.

```clojure
(let [strings (filter string? (range 23))]
  (when strings
    (println "i found strings")))
```

I know there's more to this. I haven't thought about the tricky edge cases, eg

```clojure
(let [strings (seq (filter string? (range 23)))]
  (when strings
    (println "i found strings")))
```

Here the `seq` call will nil-pun in the let form and the check now is doing when the coder intends.

Also, I suppose this linter would need to be enabled/disabled so it will need a name and I haven't thought about that.

**Additional context**
I understand this might be possible, flaky, or impossible. Just tossing it out there. Perhaps this isn't hit often in real world code? It did come up in a real world PR but I don't see it often. I'm not sure if there is type information sufficient to discern if `seq` or `not-empty` has already been run on the seq.

**Comment by borkdude** [comment] 2021-12-06 18:36
I just found out that this is a duplicate of https://github.com/clj-kondo/clj-kondo/issues/721. Feel free to upvote that one using a thumbs up.

**Closed by borkdude** 2021-12-06 18:36 UTC
